from __future__ import annotations

import json
import re
from dataclasses import dataclass
from pathlib import PurePosixPath

from cuanta.domain.affected import is_test_file
from cuanta.domain.code_index import HandlingCard, IndexedFile, IndexRow
from cuanta.domain.spectrum import BYTES_PER_TOKEN, estimated_tokens

_SENSITIVE = re.compile(r"auth|payment|billing|secret|credential|permission|security", re.I)
_GENERATED = re.compile(r"generated|do[ -]not[ -]edit|autogenerated", re.I)
_DO_NOT_EDIT = re.compile(r"do[ -]not[ -]edit|autogenerated|@generated", re.I)
_FAILURE = re.compile(r"reject|fail|error|retry|rollback", re.I)


@dataclass(frozen=True, slots=True)
class _Piece:
    prefix: str
    text: str


def _bytes(text: str) -> int:
    return len(text.encode("utf-8"))


def _clip(text: str, budget: int) -> str:
    if _bytes(text) <= budget:
        return text
    if budget < 4:
        return ""
    value = text.encode("utf-8")[: budget - 3].decode("utf-8", errors="ignore").rstrip()
    if " " in value and len(value.rsplit(" ", 1)[0]) >= len(value) // 2:
        value = value.rsplit(" ", 1)[0]
    return value + "…" if value else ""


def _one_line(text: str) -> str:
    lines: list[str] = []
    fence = ""
    for line in text.splitlines():
        value = line.strip()
        if value.startswith(("```", "~~~")):
            marker = value[:3]
            fence = "" if fence == marker else marker
        elif not fence and not value.startswith("#"):
            lines.append(value.removeprefix("- ").removeprefix("* "))
    return " ".join(" ".join(lines).split())


def _fresh(rows: tuple[IndexRow, ...], file: IndexedFile) -> tuple[IndexRow, ...]:
    valid = (
        row
        for row in rows
        if not row.stale and (row.path != file.path or row.source_hash == file.content_hash)
    )
    return tuple(
        sorted(
            set(valid),
            key=lambda row: (
                row.path,
                row.line,
                row.end_line,
                row.relation,
                row.text,
                row.id,
                row.provenance,
                row.target,
                row.source_hash,
                row.confidence,
            ),
        )
    )


def _role(file: IndexedFile, symbols: tuple[IndexRow, ...]) -> str:
    path = PurePosixPath(file.path)
    parts = {part.lower() for part in path.parts}
    name = path.name.lower()
    if is_test_file(file.path) or parts & {"tests", "test", "__tests__"}:
        return "test"
    if path.suffix.lower() in {".css", ".scss", ".sass", ".less"}:
        return "styles"
    if "routes" in parts or any(row.relation == "route" for row in symbols):
        return "route"
    if "app" in parts and path.stem.lower() in {"page", "layout", "route"}:
        return "route"
    if "hooks" in parts or re.match(r"use[A-Z]", path.stem):
        return "hook"
    if parts & {"stores", "store"} or name.endswith(("store.ts", "store.js", "store.py")):
        return "store"
    if parts & {"services", "service"} or name.endswith(("service.ts", "service.py")):
        return "service"
    if parts & {"components", "component"} or path.suffix.lower() in {".tsx", ".jsx"}:
        return "component"
    if path.suffix.lower() in {".json", ".toml", ".yaml", ".yml", ".ini"} or "config" in name:
        return "config"
    return "code"


def _purpose(
    file: IndexedFile, role: str, symbols: tuple[IndexRow, ...], notes: tuple[IndexRow, ...]
) -> str:
    ranked = sorted(
        notes,
        key=lambda row: (
            0
            if row.provenance.startswith("agent-note:") or row.relation == "note"
            else 1
            if row.relation == "finding"
            else 2
            if row.relation == "summary" or row.provenance.startswith("economy")
            else 3,
            row.path,
            row.line,
            row.id,
        ),
    )
    for row in ranked:
        value = _one_line(row.text)
        if value:
            return value
    names = tuple(dict.fromkeys(row.text for row in symbols if row.text))
    subject = ", ".join(names[:3]) or PurePosixPath(file.path).stem
    return f"{role.capitalize()} for {subject}."


def _anchor(row: IndexRow) -> str:
    if not row.line:
        return row.path
    end = f"-{row.end_line}" if row.end_line > row.line else ""
    return f"{row.path}:{row.line}{end}"


def _source(row: IndexRow) -> str:
    if row.provenance.startswith("agent-note:"):
        return "agent-note"
    return row.provenance.split("#", 1)[0]


def _risk(
    file: IndexedFile,
    symbols: tuple[IndexRow, ...],
    incoming: tuple[IndexRow, ...],
    outgoing: tuple[IndexRow, ...],
) -> _Piece:
    importing = {row.path for row in incoming if row.path != file.path}
    targets = {
        row.target
        for row in outgoing
        if row.target
        and row.target != file.path
        and not row.target.startswith(("symbol:", file.path + ":"))
    }
    exports = {row.target or row.text for row in outgoing if row.relation == "exports"}
    names = " ".join(row.text for row in symbols)
    sensitive = "; sensitive" if _SENSITIVE.search(file.path + " " + names) else ""
    return _Piece(
        "Risk ",
        f"fan-in={len(importing)} centrality={len(importing | targets)} "
        f"exports={len(exports)}{sensitive}",
    )


def _pitfall(row: IndexRow) -> _Piece | None:
    try:
        data: object = json.loads(row.text)
    except ValueError:
        data = None
    if isinstance(data, dict):
        action = str(data.get("action", row.relation))
        outcome = str(data.get("outcome", ""))
        retries = str(data.get("retries", 0))
        signature = str(data.get("signature", ""))
        if not _FAILURE.search(action + " " + outcome + " " + signature) and retries == "0":
            return None
        value = f"{outcome} {action}".strip()
        if retries != "0":
            value += f" retries={retries}"
        if signature:
            value += "; " + signature
    elif _FAILURE.search(row.relation + " " + row.text):
        value = _one_line(row.text) or row.relation
    else:
        return None
    return _Piece(f"Pitfall {row.provenance}: ", value)


def _minimum(piece: _Piece) -> int:
    if piece.prefix in {"Risk ", "Flags "}:
        return _bytes(piece.prefix + piece.text)
    return _bytes(piece.prefix) + min(_bytes(piece.text), 24)


def _pack(header: str, pieces: tuple[_Piece, ...], budget: int) -> str:
    chosen: list[_Piece] = []
    available = budget - _bytes(header)
    for piece in pieces:
        size = _minimum(piece) + 1
        if piece.text and size <= available:
            chosen.append(piece)
            available -= size
    lines = [header]
    remaining = budget - _bytes(header)
    for offset, piece in enumerate(chosen):
        reserve = sum(_minimum(later) + 1 for later in chosen[offset + 1 :])
        extra = max(0, remaining - reserve - _minimum(piece) - 1)
        share = extra // (len(chosen) - offset)
        allowance = _minimum(piece) - _bytes(piece.prefix) + share
        line = piece.prefix + _clip(piece.text, allowance)
        lines.append(line)
        remaining -= _bytes(line) + 1
    return "\n".join(lines)


def _applies(row: IndexRow, path: str) -> bool:
    if row.target == "**":
        return True
    if row.target.endswith("/**"):
        return path.startswith(row.target.removesuffix("**"))
    return row.target == path


def _evidence(
    rules: tuple[IndexRow, ...],
    tests: tuple[IndexRow, ...],
    notes: tuple[IndexRow, ...],
    history: tuple[IndexRow, ...],
) -> tuple[_Piece, ...]:
    groups = (
        tuple(_Piece(f"Rules {row.provenance}: ", _one_line(row.text)) for row in rules),
        tuple(
            _Piece(f"Tests {_anchor(row)}: ", _one_line(row.text) or "imports this file")
            for row in tests
        ),
        tuple(piece for row in history if (piece := _pitfall(row)) is not None),
        tuple(
            _Piece(f"Fact {_anchor(row)} [{_source(row)}]: ", _one_line(row.text))
            for row in notes
            if row.target.startswith("anchor:") and row.relation in {"note", "finding"}
        ),
    )
    return tuple(group[0] for group in groups if group) + tuple(
        piece for group in groups for piece in group[1:]
    )


def handling_card(
    file: IndexedFile,
    symbols: tuple[IndexRow, ...],
    incoming: tuple[IndexRow, ...],
    outgoing: tuple[IndexRow, ...],
    notes: tuple[IndexRow, ...],
    rules: tuple[IndexRow, ...],
    tests: tuple[IndexRow, ...],
    history: tuple[IndexRow, ...],
    limit: int = 120,
) -> HandlingCard:
    if limit <= 0:
        raise ValueError("A handling card requires a positive token limit")
    symbols, incoming, outgoing, notes, rules, tests, history = (
        _fresh(rows, file) for rows in (symbols, incoming, outgoing, notes, rules, tests, history)
    )
    symbols = tuple(row for row in symbols if row.path == file.path)
    incoming = tuple(row for row in incoming if row.target == file.path)
    outgoing = tuple(row for row in outgoing if row.path == file.path)
    notes = tuple(
        row for row in notes if row.path == file.path and row.target.startswith("anchor:")
    )
    rules = tuple(row for row in rules if _applies(row, file.path))
    tests = tuple(row for row in tests if row.target == file.path)
    history = tuple(row for row in history if row.path == file.path)
    role = _role(file, symbols)
    purpose = _clip(_purpose(file, role, symbols, notes), 120)
    header = f"{file.path} | {role}"
    budget = max(int(limit * BYTES_PER_TOKEN), _bytes(header))
    pieces = [_Piece("Purpose ", purpose), _risk(file, symbols, incoming, outgoing)]
    evidence = " ".join(row.text for row in notes + rules)
    if _GENERATED.search(file.path) or _DO_NOT_EDIT.search(evidence):
        pieces.append(_Piece("Flags ", "generated; do-not-edit"))
    pieces.extend(_evidence(rules, tests, notes, history))
    text = _pack(header, tuple(pieces), budget)
    return HandlingCard(file.path, text, estimated_tokens(_bytes(text)), role, purpose)
