from __future__ import annotations

from collections.abc import Mapping, Sequence
from typing import Protocol

from cuanta.domain.code_index import IndexedFile, IndexRow, IndexTable


class CodeIndex(Protocol):
    def files(self) -> tuple[IndexedFile, ...]: ...

    def rows(self, table: IndexTable, path: str = "") -> tuple[IndexRow, ...]: ...

    def replace_files(self, files: Sequence[IndexedFile], removed: Sequence[str]) -> None: ...

    def put_rows(self, table: IndexTable, rows: Sequence[IndexRow]) -> None: ...

    def meta(self) -> Mapping[str, str]: ...

    def set_meta(self, values: Mapping[str, str]) -> None: ...

    def close(self) -> None: ...


class IndexInventory(Protocol):
    def candidates(self) -> tuple[IndexedFile, ...]: ...

    def read(self, path: str) -> str | None: ...
