from __future__ import annotations

from typing import Protocol

from cuanta.domain.forge_state import InstallSummary


class ForgeKit(Protocol):
    def install(self, dry_run: bool, missing_only: bool = False) -> InstallSummary: ...

    def init_prompt(self) -> str: ...

    def refresh_prompt(self) -> str: ...

    def installed_skill(self) -> str | None: ...

    def vendored_skill(self) -> str: ...

    def vendored_version(self) -> str: ...

    def mandate_template(self) -> str: ...

    def skill_path(self) -> str: ...
