from __future__ import annotations

from collections.abc import Sequence
from dataclasses import dataclass
from typing import Protocol

from cuanta.domain.ledger import (
    Baseline,
    Capsule,
    Decision,
    LedgerEvent,
    RouteAudit,
    RoutingDecision,
    Run,
    SignatureRecord,
    Snapshot,
    TestRunRecord,
)


@dataclass(frozen=True, slots=True)
class EventQuery:
    run_id: str = ""
    session_id: str = ""
    since: str = ""
    trace_id: str = ""
    limit: int = 0


class Ledger(Protocol):
    def schema_version(self) -> int: ...

    def add_run(self, run: Run) -> None: ...

    def update_run(self, run: Run) -> None: ...

    def get_run(self, run_id: str) -> Run | None: ...

    def runs(self, kind: str = "", hu_ref: str = "", limit: int = 0) -> tuple[Run, ...]: ...

    def run_by_trace(self, trace_id: str) -> Run | None: ...

    def add_events(self, events: Sequence[LedgerEvent]) -> int: ...

    def events(self, query: EventQuery) -> tuple[LedgerEvent, ...]: ...

    def delete_events(self, source: str) -> int: ...

    def add_test_run(
        self, record: TestRunRecord, signatures: Sequence[SignatureRecord]
    ) -> None: ...

    def test_runs(self, run_id: str = "", limit: int = 0) -> tuple[TestRunRecord, ...]: ...

    def signatures(self, test_run_id: str) -> tuple[SignatureRecord, ...]: ...

    def signature_history(self, signature_id: str) -> tuple[TestRunRecord, ...]: ...

    def add_capsule(self, capsule: Capsule) -> None: ...

    def get_capsule(self, reference: str) -> Capsule | None: ...

    def add_decision(self, decision: Decision) -> int: ...

    def set_decision_outcome(self, decision_id: int, outcome: str) -> None: ...

    def decisions(self, run_id: str = "", limit: int = 0) -> tuple[Decision, ...]: ...

    def preview_decision(self, request_hash: str, question: str) -> int | None: ...

    def link_decisions(self, request_hash: str, run_id: str) -> int: ...

    def close_run_decisions(self, run_id: str, outcome: str) -> None: ...

    def add_routing_decision(self, decision: RoutingDecision) -> int: ...

    def routing_decisions(
        self, run_id: str = "", limit: int = 0
    ) -> tuple[RoutingDecision, ...]: ...

    def set_routing_outcome(
        self, run_id: str, outcome: str, cost_usd: float | None, retries: int
    ) -> None: ...

    def set_routing_accepted(self, run_id: str, accepted: bool) -> None: ...

    def add_route_audits(self, audits: Sequence[RouteAudit]) -> None: ...

    def route_audits(self, run_id: str) -> tuple[RouteAudit, ...]: ...

    def add_snapshots(self, snapshots: Sequence[Snapshot]) -> None: ...

    def snapshots(self, run_id: str, phase: str) -> tuple[Snapshot, ...]: ...

    def add_baselines(self, baselines: Sequence[Baseline]) -> None: ...

    def baselines(self, run_id: str = "") -> tuple[Baseline, ...]: ...

    def close(self) -> None: ...
